<?php

namespace Iotronlab\FilamentMultiGuard\Http\Livewire\Auth;

use Filament\Facades\Filament;
use Filament\FilamentManager;
use Filament\Http\Livewire\Auth\Login as FilamentLogin;
use Illuminate\Contracts\View\View;
use Iotronlab\FilamentMultiGuard\Facades\FilamentMultiGuard;

class Login extends FilamentLogin
{


    public ?string $heading = 'Sign in to your account';
    public string $currentPath;
    public string  $currentContext;

    public function mount(): void
    {
        $this->currentContext = Filament::currentContext();
        $this->currentPath = config(Filament::currentContext())['path'];

        parent::mount(); // TODO: Change the autogenerated stub
    }


    public function render(): View
    {


        return \view('filament-multi-guard::login')->layout("filament::components.layouts.base", [
            "title" => __("filament::login.title"),
        ]);

    }

}
